import {ArrowUpRight,ArrowDown,MessageCircle,MapPin,Phone,Lightbulb,AudioLines,Armchair,Wrench} from 'lucide-react';
const maps='https://maps.app.goo.gl/vfyh5b5weHkkD34L6';
const enquiry=(service='car upgrades')=>`https://wa.me/919845004858?text=${encodeURIComponent(`Hi Auto Style, I am interested in ${service}. My car model is: ___. Could you share suitable options and a quote?`)}`;
const services=[{n:'01',name:'Light up the road.',type:'LIGHTING',text:'Explore headlight and lighting options that suit your vehicle. Ask about compatibility and installation.',icon:Lightbulb,topic:'lighting upgrades'},{n:'02',name:'Feel every track.',type:'AUDIO & INFOTAINMENT',text:'Bring your listening preferences. Start a conversation about speakers, sound systems and connected screens.',icon:AudioLines,topic:'audio and infotainment upgrades'},{n:'03',name:'Make comfort personal.',type:'INTERIOR ACCESSORIES',text:'Explore cabin accessories and finishing touches for your everyday drive, matched to your car and your style.',icon:Armchair,topic:'interior accessories'},{n:'04',name:'A presence of its own.',type:'EXTERIOR & SUV STYLING',text:'From subtle details to a stronger SUV look. Discuss accessories, fitment and the direction you have in mind.',icon:Wrench,topic:'exterior and SUV accessories'}];
export default function Home(){return <main id="top">
<a className="skip-link" href="#upgrades">Skip to upgrades</a><div className="preview-bar">WEBSITE CONCEPT <span>Prepared for Auto Style Koramangala by PEKIFLOW</span></div>
<header className="header wrap"><a className="wordmark" href="#top" aria-label="Auto Style home">AUTO<span>STYLE</span><small>KORAMANGALA / BENGALURU</small></a><nav aria-label="Main navigation"><a href="#upgrades">Upgrades</a><a href="#approach">The approach</a><a href="#visit">Visit us</a></nav><a className="header-cta" href={enquiry()} target="_blank" rel="noopener noreferrer">LET’S TALK <ArrowUpRight size={18}/></a></header>
<section className="hero" aria-labelledby="hero-title"><img className="hero-img" src="/images/suv-hero.webp" alt="Illustrative graphite SUV with white headlights in a dark automotive studio" width="1672" height="941" fetchPriority="high"/><div className="hero-shade"/><div className="hero-content wrap"><p className="eyebrow"><span/>YOUR CAR. YOUR SIGNATURE.</p><h1 id="hero-title">DRIVE<br/>SOMETHING<br/><em>PERSONAL.</em></h1><p className="hero-desc">Car accessories. Considered upgrades.<br/>A whole new feeling behind the wheel.</p><div className="hero-actions"><a className="button lime" href={enquiry()} target="_blank" rel="noopener noreferrer">PLAN YOUR UPGRADE <ArrowUpRight size={20}/></a><a className="explore" href="#upgrades">Explore upgrades <ArrowDown size={17}/></a></div></div><div className="hero-footer wrap"><span><MapPin size={15}/>KORAMANGALA, BENGALURU</span><span>ILLUSTRATIVE CONCEPT IMAGE</span><a href="#upgrades" aria-label="Scroll to upgrades"><ArrowDown size={22}/></a></div></section>
<div className="category-strip" aria-label="Upgrade categories"><span>LIGHTING</span><i>+</i><span>AUDIO</span><i>+</i><span>INTERIORS</span><i>+</i><span>SUV STYLING</span><i>+</i><span>ACCESSORIES</span></div>
<section className="section wrap" id="upgrades"><div className="section-heading"><div><p className="eyebrow">01 / THE UPGRADE EDIT</p><h2>THE DETAILS<br/>MAKE THE <em>DRIVE.</em></h2></div><p>A better soundtrack. A more comfortable cabin.<br/>A look that feels like you.<br/>Start with what matters to your drive.</p></div><div className="service-grid">{services.map(s=><a key={s.n} className="service" href={enquiry(s.topic)} target="_blank" rel="noopener noreferrer"><div className="service-top"><span>{s.n} / {s.type}</span><s.icon size={30} strokeWidth={1.25}/></div><h3>{s.name}</h3><p>{s.text}</p><div className="service-link">EXPLORE OPTIONS <ArrowUpRight size={20}/></div></a>)}</div><p className="availability">Discuss current product availability, vehicle fitment and pricing directly with the store.</p></section>
<section className="statement" id="approach"><div className="wrap statement-grid"><p className="eyebrow">02 / BUILT AROUND YOU</p><div><h2>YOUR CAR ISN’T<br/>JUST A MODEL.<br/><span>IT’S YOURS.</span></h2><p>The daily commute. The weekend escape. The playlist you know by heart. Your upgrades should start with how you actually use your car.</p><a className="text-cta" href={enquiry('a personalized upgrade plan')} target="_blank" rel="noopener noreferrer">LET’S FIND YOUR NEXT UPGRADE <ArrowUpRight size={22}/></a></div><span className="statement-mark" aria-hidden="true">AS/</span></div></section>
<section className="process section wrap"><div className="section-heading"><div><p className="eyebrow">03 / FROM IDEA TO DRIVE</p><h2>A CLEAR ROUTE<br/>TO YOUR <em>UPGRADE.</em></h2></div><a className="button outline" href={enquiry()} target="_blank" rel="noopener noreferrer"><MessageCircle size={18}/>START ON WHATSAPP</a></div><div className="steps">{[{n:'01',title:'Tell us your drive.',text:'Share your car model, year and the upgrade you have in mind. A reference photo helps too.'},{n:'02',title:'Explore the options.',text:'Ask about compatible products, the complete quote and what installation involves.'},{n:'03',title:'Plan your visit.',text:'Confirm availability and a convenient time with the store before coming in.'}].map(s=><article key={s.n}><span>{s.n}<ArrowUpRight size={22}/></span><h3>{s.title}</h3><p>{s.text}</p></article>)}</div></section>
<section className="contact" id="visit"><div className="wrap contact-grid"><div><p className="eyebrow">04 / AUTO STYLE KORAMANGALA</p><h2>YOUR NEXT<br/>UPGRADE<br/><em>STARTS HERE.</em></h2><a className="button lime" href={enquiry()} target="_blank" rel="noopener noreferrer">LET’S TALK ABOUT YOUR CAR <ArrowUpRight size={20}/></a></div><div className="contact-info"><p className="contact-intro">Have something in mind?<br/>Bring the idea. Let’s talk details.</p><a href={maps} target="_blank" rel="noopener noreferrer"><div><span>FIND THE STORE</span><strong>Koramangala, Bengaluru</strong><small>Open location & directions</small></div><MapPin size={25}/></a><a href="tel:+919845004858"><div><span>CALL AUTO STYLE</span><strong>+91 98450 04858</strong><small>Confirm store hours before visiting</small></div><Phone size={23}/></a><a href={enquiry()} target="_blank" rel="noopener noreferrer"><div><span>YOUR CAR. YOUR QUESTIONS.</span><strong>Chat on WhatsApp</strong><small>Share your model and upgrade ideas</small></div><MessageCircle size={25}/></a></div></div></section>
<footer className="footer wrap"><a className="wordmark" href="#top">AUTO<span>STYLE</span><small>KORAMANGALA / BENGALURU</small></a><p>Independent website concept by PEKIFLOW.<br/>Illustrative imagery. Service categories and contact details require owner confirmation.</p><a href="#top">BACK TO TOP <ArrowUpRight size={16}/></a></footer><a className="mobile-cta" href={enquiry()} target="_blank" rel="noopener noreferrer"><MessageCircle size={20}/>PLAN YOUR UPGRADE <ArrowUpRight size={20}/></a>
</main>}
